version: '3'

services:
 db:
   image: mysql:5.7
   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
   volumes:
     - dbdata:/var/lib/mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: sns
     MYSQL_USER: akita
     MYSQL_PASSWORD: akitakaito
   ports:
     - "3307:3306"

 web:
   build:
     context: .
     dockerfile: docker/django/Dockerfile
   environment:
      - DATABASE_HOST=db
   command: ["./docker/django/wait-for-mysql.sh", "db"]
   volumes:
     - .:/app
   ports:
     - "8080:8000"
   depends_on:
     - db
volumes:
  dbdata: