# Generated by Django 2.1.4 on 2018-12-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
