# Generated by Django 2.1.4 on 2018-12-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_token_is_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
